# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Exit with success
        run: |
          exit 0 | tee hoge.log

      - name: Exit with fail
        run: |
          exit 1 | tee hoge.log

      - name: Exit with success
        run: |
          set -o pipefail
          exit 0 | tee hoge.log

      - name: Exit with fail
        run: |
          set -o pipefail
          exit 1 | tee hoge.log
